services:
  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: ifoodme-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # 使用系统的 Let's Encrypt 证书
      - ./nginx/logs:/var/log/nginx
      - ./client/dist:/var/www/html:ro  # 客户端前端静态文件
      - ./admin/dist:/var/www/admin/dist:ro  # 管理后台静态文件
    depends_on:
      - ar-backend
    networks:
      - app-network
    restart: unless-stopped

  # Go 后端服务
  ar-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ifoodme-backend
    environment:
      # 重写数据库 host 为 docker 服务名
      - BLUEPRINT_DB_HOST=postgres
      - ENVIRONMENT=production
      - FRONTEND_URL=https://www.ifoodme.com
      - GOOGLE_CALLBACK_URL=https://www.ifoodme.com/api/auth/google/callback
      - COOKIE_DOMAIN=.ifoodme.com
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: ifoodme-postgres
    environment:
      - POSTGRES_DB=${BLUEPRINT_DB_DATABASE}
      - POSTGRES_USER=${BLUEPRINT_DB_USERNAME}
      - POSTGRES_PASSWORD=${BLUEPRINT_DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql_script:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BLUEPRINT_DB_USERNAME} -d ${BLUEPRINT_DB_DATABASE}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # PgAdmin 管理工具（可选）
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ifoodme-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ifoodme.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "9080:80"  # 只绑定到本地地址
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped
    profiles:
      - admin  # 使用 profile，默认不启动

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
